Add ttl to be accepted as a function
groupby/buffering-cache pull request #20
Opened 2021-10-27 21:11 UTC by SadatAhmed-GBI

2021-10-27 21:34 UTC, mattwelke requested changes
Good way to implement changes. I like the fact that we contain the logic of deciding whether to treat the provided config as a function or not to a single area and then use the value throughout the rest of the logic, so we have as few places as possible to change.

I had a suggestion for a test to add. See comment.

Also, I think we should add more error handling. With this PR's change, we will have code that says "if provided config is not a function and not a number, throw an error". The problem is we won't know until run time when something is first saved in the cache whether the value returned by the function provided is valid. So we should add error handling during the cache saving parts that validates the value returned by the function and throws an error (making the save operation an error) if it is invalid. I think this would be a non breaking change because the client presumably is already catching errors from cache save operations. There's always been the possibility of a Redis error during the save.

2021-10-27 21:34 UTC, mattwelke commented on lib/cache.js
> +            overrideTtl || ttlToUse
Can be cleaned up by moving self.getTtl() to line 48 and removing ttlToUse. It's implied that it's the TTL to be used because it's the data to be returned.

2021-10-27 21:34 UTC, mattwelke commented on lib/cache.js
> +                overrideTtl || ttlToUse
Same as above.

2021-10-27 21:34 UTC, mattwelke commented on tests/cache.spec.js
> +    });
Test is good but we should also add a test for how the function is used. We should duplicate one of our integration tests and provide the config as a function instead of a fixed value. It's fine if the function returns a fixed value. Then we'd assert that the cache is hit or missed as we expected it to be. Assertions would be the same as the assertions we have for the fixed value test right now, assuming the function we provide returns the same fixed value.

2021-10-27 22:13 UTC, SadatAhmed-GBI commented on tests/cache.spec.js
> +    });
yeah that makes sense!!

2021-10-28 20:23 UTC, mattwelke requested changes

2021-10-28 20:23 UTC, mattwelke commented on lib/cache.js
> +            throw new Error('ttl must be a number greater than 0 or a function which returns a number greater than 0');
Need to test for gte 0 too. Right now, this just tests for is a number or not.

2021-10-28 20:49 UTC, mattwelke submitted a review, later dismissed
🚢

2021-10-28 21:45 UTC, mattwelke approved these changes

2021-10-29 16:58 UTC, merged